name: share
description: Flutter plugin for sharing content via the platform share UI, using
  the ACTION_SEND intent on Android and UIActivityViewController on iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/share
version: 2.0.0-nullsafety.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.share
        pluginClass: SharePlugin
      ios:
        pluginClass: FLTSharePlugin

dependencies:
  meta: ^1.2.4
  mime: ^0.9.7
  flutter:
    sdk: flutter

environment:
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.10.0-0 <3.0.0"
